services:
    - docker

install:
    - echo "nothing needs to be installed"

before_script:
    - echo "no tests"

script:
    - docker --version
    - docker build -t simple-node
    - docker tag simple-node jdkeithdcg/simple-node:latest

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push jdkeithdcg/simple-node:latest